# Generated by Django 5.2.4 on 2025-07-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['hotel', 'price'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='mark',
        ),
        migrations.AddField(
            model_name='rooms',
            name='date_end_booked',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца бронирования'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='date_start_booked',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала бронирования'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.IntegerField(choices=[(0, 'Зарезервирован'), (1, 'Свободен')], db_index=True, default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='sleep_places',
            field=models.PositiveSmallIntegerField(verbose_name='Количество спальных мест'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название номера'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel_numbers.hotels', verbose_name='Отель'),
        ),
    ]
